### ISSUE TITLE
Problem with URL

### ISSUE THREAD

**Issue by HendrikKoelbel** [ahegazy/php-mvc-skeleton#1]
I set up the project properly and got it running on my server.  However, there is a problem with the URL splitting. 
https://example.com///home/login <-- this is the default page
<img width="1502" alt="500 internal server error 2019-02-26 17-19-45" src="https://user-images.githubusercontent.com/31684940/53428939-f3afe700-39eb-11e9-8791-b2bc6891fb0c.png">

**Comment by Hendrik-Koelbel** [comment]
That might be the problem.  The variable $language is undefined and the variable $lang

<img width="1680" alt="php-mvc-skeleton" src="https://user-images.githubusercontent.com/31684940/53429251-8c466700-39ec-11e9-8f8d-d4624b35a74e.png">
<img width="1680" alt="php-mvc-skeleton2" src="https://user-images.githubusercontent.com/31684940/53429258-91a3b180-39ec-11e9-9541-20651dcfe555.png">

**Comment by ahegazy** [comment]
Hi @Hendrik-Koelbel , 
Thank you for your report. 
I now have seen the issue and pushed commit #[5ee193f](https://github.com/ahegazy/php-mvc-skeleton/commit/ed51bf88c4c7045aa53bc6096f63523ba4c3c6df) fixing it, try the last version and tell me. 

**Further illustration**

-  The constructor in [core/App.php](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/App.php) was using a variable _$language_ which is defined in the class, but i should have referenced to it using _$this->language_
so [line 28](https://github.com/ahegazy/php-mvc-skeleton/blob/5ee193f1ef7067a3b8802935996b22a75bd9cb48/app/core/App.php#L28) should be 
`define('LANGUAGE', $this->language);`
and for further precaution I've edited the condition in [line 25](https://github.com/ahegazy/php-mvc-skeleton/blob/5ee193f1ef7067a3b8802935996b22a75bd9cb48/app/core/App.php#L25) to be 
`if($req != NULL && file_exists('../app/languages/' . $req[0])){`

- For the [core/Controller.php](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php)  the variable _$lang_ is actually defined when you import the language file. 
so lines [47](https://github.com/ahegazy/php-mvc-skeleton/blob/5ee193f1ef7067a3b8802935996b22a75bd9cb48/app/core/Controller.php#L47) and [53](https://github.com/ahegazy/php-mvc-skeleton/blob/5ee193f1ef7067a3b8802935996b22a75bd9cb48/app/core/Controller.php#L53) are correct.

**However**, these issues weren't causing an internal server error, only undefined variables, so i encourage you to check the server logs for any other issues.

**Comment by Hendrik-Koelbel** [comment]
Now "en" is contained in the URL. However, there is still a / in the URL too much.

<img width="1431" alt="internal server error" src="https://user-images.githubusercontent.com/31684940/53443288-a5aadb80-3a0b-11e9-85d1-f20fdcd63013.png">

But if you are planning an update in the future, would it be possible to make the different language files into a single file? 
for example: 
```
language       (one file for all)
├── en
│   └── en.php 
├── de
│   └── de.php 
└── fr 
    └── fr.php
```
That would be a great thing and easier in dealing with the language files. 
With kind regards Hendrik Kölbel

**Comment by ahegazy** [comment]
@Hendrik-Koelbel The parser wouldn't care how many slashes _/_ in the url, the parameters will be parsed correctly.
you should check the logs for this internal server error.

your suggestion regarding language part is actually easier to implement, but you'll load a bulk of unneeded values in an array that you may never use. 
anyway, if you want to you can do it easily by editing [core/Controller.php](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/core/Controller.php) and removing the conditions in line [45](https://github.com/ahegazy/php-mvc-skeleton/blob/4d190a662661d255baa2f0f08fc8fdd6b0c473bb/app/core/Controller.php#L52) and the condition in line [52](https://github.com/ahegazy/php-mvc-skeleton/blob/4d190a662661d255baa2f0f08fc8fdd6b0c473bb/app/core/Controller.php#L52), and replacing them with:

` require_once("../app/languages/" . LANGUAGE . "/". LANGUAGE .".php");`
` /* $lang is an array that is defined in the language file. */`
`$data['lang']= $lang;`
and all the language data will be stored in _$data['lang']_.

**NOTE** I've reversed the last commit regarding the _$lang_ and edited the comment above, kindly check it.
