### ISSUE TITLE
Route in php-mvc-skeleton

### ISSUE THREAD

**Issue by sudipsingh04** [ahegazy/php-mvc-skeleton#2]
Not able to create custom route. How can this be implemented? 
How can we access the controller via route?

**Comment by ahegazy** [comment]
Hi @sudipsingh04 To create a custom route, you have to:-
1. create a [controller ](https://github.com/ahegazy/php-mvc-skeleton/tree/master/app/controllers) class for that route so it would open like _yousite.com/YOURCLASS/YOURMETHOD_ or add a method with its name in the [home](https://github.com/ahegazy/php-mvc-skeleton/blob/master/app/controllers/home.php) class so it would be like _yousite.com/home/YOURMETHOD_
2. Then you create a [model](https://github.com/ahegazy/php-mvc-skeleton/tree/master/app/models) to manage the logic and the functionality of your new page if you want.
3. Finally, you have to create a [view ](https://github.com/ahegazy/php-mvc-skeleton/tree/master/app/views) for this method inside your class directory or [home ](https://github.com/ahegazy/php-mvc-skeleton/tree/master/app/views/home) class directory. 

- hope i answered your question, if you need anything else don't hesitate asking.

---
**Ahmad Hegazy**.

edit: styling.

**Comment by ahegazy** [comment]
Closed. Not an issue, no response.
